name: curufic_abc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0" #There is no null-safety

dependencies: # some of these dependencies are downgraded for reason...if u still want to upgrade make sure u have alternative 
  platform: ^3.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: ^0.9.8+1
  path_provider:
  path:
  font_awesome_flutter: ^8.11.0
  sqflite: ^1.3.0
  fl_chart: ^0.30.0
  flutter_local_notifications: ^5.0.0
  flutter_native_timezone: ^1.0.10
  flutter_bloc: ^3.2.0
  easy_localization: ^3.0.0
  device_info: ^2.0.0
  table_calendar: ^2.3.3
  image_picker: ^0.7.0
  crypto: ^3.0.1
  hex: ^0.2.0
  dio: ^4.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  syncfusion_flutter_pdf: ^18.4.49-beta
  open_file: ^3.2.1
  string_similarity: ^2.0.0
  dcdg: ^3.1.1
flutter:
  uses-material-design: true
  assets:
    - lib/lang/en.json
    # - images/ee.jpeg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
